type: node

ignoreNotice: true

paths:
  - km.*
  - config.*
  - index.js
  - package.json

only:
  test:
    - script:
      - npm install --production
      - npm run release:test
  master:
    - script:
      - npm install --production
      - npm run release
